In [1]:
import arcpy
import os
import pandas as pd
arcpy.env.overwriteOutput = True
arcpy.env.outputCoordinateSystem = None

In [2]:
# paths
repo_folder = r"C:/Users/Chels/OneDrive - University of Illinois - Urbana/Ch6_CASC_Project/Dual-Risk-Repo"
old_project_folder = r"C:/Users/Chels/OneDrive - University of Illinois - Urbana/Ch5_Sackett_Impacts"
census_gdb = os.path.normpath(os.path.join(old_project_folder, "Wetland Mapping/TIGER_Line_Census.gdb"))
climate_impacts_gdb = r"F:/Wetland_Climate_Impacts/Wetland Climate Impacts.gdb"

In [3]:
# read in updated county area totals for 2024
totals_2024_df = pd.read_csv(os.path.normpath(os.path.join(repo_folder,"County_Summaries/wetland_area_totals/step2_2024_nonwotus_locally_unprotected_area_county_wetland_area_totals.csv")))

In [4]:
totals_2024_df

,NAME,mean_PF_nhd,min_PF_nhd,max_PF_nhd,mean_IE_nhd,min_IE_nhd,max_IE_nhd,mean_SPF_nhd,min_SPF_nhd,max_SPF_nhd,...,max_IE_brinkerhoff,mean_SPF_brinkerhoff,min_SPF_brinkerhoff,max_SPF_brinkerhoff,mean_SFS_brinkerhoff,min_SFS_brinkerhoff,max_SFS_brinkerhoff,mean_SF_brinkerhoff,min_SF_brinkerhoff,max_SF_brinkerhoff
0,Adams,3868.934645,3868.934645,3868.934645,3247.417884,3236.909591,3257.297934,3216.168112,3197.922451,3233.582335,...,3661.314001,3640.008902,3631.839204,3647.855011,3640.008902,3631.839204,3647.855011,3345.102754,3311.388361,3377.965670
1,Alexander,4870.835018,4870.835018,4870.835018,4837.671159,4837.480958,4837.781151,4820.359174,4818.627500,4822.010641,...,4865.726148,4852.344625,4851.348682,4853.260359,4852.344625,4851.348682,4853.260359,2986.531025,2786.105424,3189.016474
2,Bond,2916.759065,2916.759065,2916.759065,2623.598875,2615.284944,2631.789703,2611.007100,2602.374036,2619.517060,...,2788.476121,2779.977104,2775.953230,2783.889312,2779.977104,2775.953230,2783.889312,2707.475830,2691.799617,2723.040378
3,Boone,1094.876067,1094.421757,1095.330376,1087.987286,1087.320702,1088.653870,1075.518362,1074.489478,1076.547247,...,1101.476575,1091.494233,1089.541221,1092.824982,1091.494233,1089.541221,1092.824982,705.321670,674.174717,736.102475
4,Brown,1055.844254,1055.844254,1055.844254,870.645006,865.374407,875.694617,861.216607,854.808006,867.404219,...,995.719196,992.059755,991.331908,992.749965,992.059755,991.331908,992.749965,983.559432,981.665144,985.447477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Whiteside,1921.483163,1921.483163,1921.483163,1871.578450,1870.984596,1872.172303,1843.534679,1839.958914,1847.110445,...,1893.294137,1873.360996,1871.166374,1875.482324,1873.360996,1871.166374,1875.482324,1653.928628,1619.020007,1687.579084
98,Will,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
99,Williamson,4889.796900,4889.796900,4889.796900,4481.418623,4461.865311,4500.136835,4346.137231,4289.639481,4403.905824,...,4787.715405,4692.395662,4653.222261,4732.340243,4692.395662,4653.222261,4732.340243,4294.036219,4174.829143,4410.570075
100,Winnebago,3348.182425,3348.182425,3348.182425,3229.007151,3223.383903,3234.630400,3169.937338,3151.269652,3187.870499,...,3330.219821,3305.390089,3299.724247,3311.264194,3305.390089,3299.724247,3311.264194,1549.998777,1426.435368,1672.622141
101,Woodford,1634.789929,1634.789929,1634.789929,1385.558575,1369.780429,1401.179116,1338.195816,1321.129720,1355.104307,...,1527.989580,1477.229544,1471.894697,1482.163395,1477.229544,1471.894697,1482.163395,1261.492767,1245.875209,1274.649489

In [5]:
# read in updated county area totals for 2024
differences_2024_df = pd.read_csv(os.path.normpath(os.path.join(repo_folder,"County_Summaries/wetland_area_differences/step2_nonwotus_locally_unprotected_area_county_wetland_area_differences.csv")))

In [6]:
differences_2024_df

,NAME,mean_PF_diff,mean_IE_diff,mean_SPF_diff,mean_SFS_diff,mean_SF_diff,min_PF_diff,min_IE_diff,min_SPF_diff,min_SFS_diff,min_SF_diff,max_PF_diff,max_IE_diff,max_SPF_diff,max_SFS_diff,max_SF_diff
0,Adams,15.249629,413.057480,425.632536,425.632536,453.671765,15.249629,420.710406,435.371448,435.371448,468.817086,15.249629,405.781987,416.433467,416.433467,436.696789
1,Alexander,-19.552247,8.566491,12.384285,12.384285,206.584485,-19.552247,8.636379,13.120016,13.120016,85.952601,-19.552247,8.496603,11.648553,11.648553,328.943459
2,Bond,-17.298131,145.975733,153.943318,153.943318,164.842419,-17.298131,150.657778,158.942278,158.942278,173.641855,-17.298131,141.044057,148.694727,148.694727,155.793352
3,Boone,14.600378,18.004507,21.748783,21.748783,77.980210,13.434436,16.778658,20.787931,20.787931,83.703201,15.144054,18.608093,22.087370,22.087370,76.751214
4,Brown,1.018232,124.612723,131.055399,131.055399,133.179358,1.018232,129.092098,136.647953,136.647953,138.106158,1.018232,120.316367,125.645865,125.645865,128.435578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Whiteside,-17.451027,-6.152616,2.158162,2.158162,44.345405,-17.451027,-5.416299,3.908591,3.908591,42.183868,-17.451027,-7.173859,0.049512,0.049512,42.899427
98,Will,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
99,Williamson,-10.885352,290.433211,335.486836,335.486836,398.233852,-10.885352,302.842115,352.064014,352.064014,414.124856,-10.885352,277.012628,318.069793,318.069793,378.165038
100,Winnebago,-5.392540,85.699416,121.396025,121.396025,326.975158,-5.392540,90.835339,134.328192,134.328192,366.242365,-5.392540,80.563493,109.410917,109.410917,273.145120
101,Woodford,-4.943270,141.412693,143.511809,143.511809,186.688632,-4.943270,151.815006,155.095781,155.095781,202.737342,-4.943270,130.766988,131.684447,131.684447,167.900367

In [9]:
county_layer = os.path.normpath(os.path.join(census_gdb, "tl_2025_il_county_clipped_NAD1983_Albers"))

In [10]:
# join totals to county dataframe
arcpy.management.MakeFeatureLayer(county_layer, "temp_layer");
arcpy.management.AddJoin(
    in_layer_or_view="temp_layer",
    in_field="NAME",  
    join_table=totals_2024_df,
    join_field="NAME",   
    join_type="KEEP_ALL" 
);
arcpy.conversion.ExportFeatures(
    in_features="temp_layer",
    out_features=os.path.normpath(os.path.join(climate_impacts_gdb, "Step2_Brinkerhoff_2024_County_UPNW_Totals"))
);
arcpy.management.Delete("temp_layer");

RuntimeError: Object: Error in executing tool